language: python

cache: pip

python:
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - python3 setup.py install

# command to run tests
script:
  - pytest --cov=gitrisky
  - flake8

# upload test coverage report to codecov
after_success:
  - codecov
